/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author vhjoa
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdmin
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        criarOrganização = new javax.swing.JButton();
        editarOrganização = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        criarContaAplicador = new javax.swing.JButton();
        editarContaAplicador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cadastrar = new javax.swing.JButton();
        criarContaAplicador1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        criarContaAplicador2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        criarContaAplicador3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        criarOrganização.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        criarOrganização.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create.png"))); // NOI18N
        criarOrganização.setText("Cadastrar Organização");
        criarOrganização.setEnabled(false);
        criarOrganização.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarOrganizaçãoActionPerformed(evt);
            }
        });

        editarOrganização.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editarOrganização.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        editarOrganização.setText("Buscar Organização");
        editarOrganização.setEnabled(false);
        editarOrganização.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarOrganizaçãoActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton3.setText("Buscar Usuário");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        criarContaAplicador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        criarContaAplicador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create.png"))); // NOI18N
        criarContaAplicador.setText("Cadastrar Aplicador");
        criarContaAplicador.setEnabled(false);
        criarContaAplicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarContaAplicadorActionPerformed(evt);
            }
        });

        editarContaAplicador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editarContaAplicador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        editarContaAplicador.setText("Buscar Aplicador");
        editarContaAplicador.setEnabled(false);
        editarContaAplicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarContaAplicadorActionPerformed(evt);
            }
        });

        botaoSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Aplicador");

        cadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create.png"))); // NOI18N
        cadastrar.setText("Cadastrar Usuário");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        criarContaAplicador1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        criarContaAplicador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create.png"))); // NOI18N
        criarContaAplicador1.setText("Cadastrar Vacina");
        criarContaAplicador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarContaAplicador1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Registrar Aplicação");

        criarContaAplicador2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        criarContaAplicador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create.png"))); // NOI18N
        criarContaAplicador2.setText("Cadastrar Lote/Vacina");
        criarContaAplicador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarContaAplicador2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Vacinas");

        criarContaAplicador3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        criarContaAplicador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create.png"))); // NOI18N
        criarContaAplicador3.setText("Registrar Aplicação");
        criarContaAplicador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarContaAplicador3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(criarContaAplicador, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(editarContaAplicador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(criarContaAplicador1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(criarOrganização, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editarOrganização, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(criarContaAplicador2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(criarContaAplicador3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoSair)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criarContaAplicador)
                    .addComponent(criarOrganização)
                    .addComponent(cadastrar))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarOrganização)
                    .addComponent(jButton3)
                    .addComponent(editarContaAplicador))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criarContaAplicador1)
                    .addComponent(criarContaAplicador2))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(criarContaAplicador3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criarOrganizaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarOrganizaçãoActionPerformed
        Menu.this.dispose();
        CriarOrganização nomeVariavel = new CriarOrganização();
        nomeVariavel.setVisible(true);
    }//GEN-LAST:event_criarOrganizaçãoActionPerformed

    private void editarOrganizaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarOrganizaçãoActionPerformed
        Menu.this.dispose();
        EditarOrganização nomeVariavel = new EditarOrganização();
        nomeVariavel.setVisible(true);
    }//GEN-LAST:event_editarOrganizaçãoActionPerformed

    private void editarContaAplicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarContaAplicadorActionPerformed
        Menu.this.dispose();
        EditarAplicador nomeVariavel = new EditarAplicador();
        nomeVariavel.setVisible(true);
    }//GEN-LAST:event_editarContaAplicadorActionPerformed

    private void criarContaAplicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarContaAplicadorActionPerformed
        Menu.this.dispose();
        CriarAplicador nomeVariavel = new CriarAplicador();
        nomeVariavel.setVisible(true);
    }//GEN-LAST:event_criarContaAplicadorActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        Menu.this.dispose();
        Login nomeVariavel = new Login();
        nomeVariavel.setVisible(true);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        new Cadastro().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Busca().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void criarContaAplicador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarContaAplicador1ActionPerformed
        new AdicionarVacina().setVisible(true);
        dispose();
    }//GEN-LAST:event_criarContaAplicador1ActionPerformed

    private void criarContaAplicador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarContaAplicador2ActionPerformed
        new AdicionarLote().setVisible(true);
        dispose();
    }//GEN-LAST:event_criarContaAplicador2ActionPerformed

    private void criarContaAplicador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarContaAplicador3ActionPerformed
        new Busca().setVisible(true);
        dispose();
    }//GEN-LAST:event_criarContaAplicador3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton criarContaAplicador;
    private javax.swing.JButton criarContaAplicador1;
    private javax.swing.JButton criarContaAplicador2;
    private javax.swing.JButton criarContaAplicador3;
    private javax.swing.JButton criarOrganização;
    private javax.swing.JButton editarContaAplicador;
    private javax.swing.JButton editarOrganização;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
